# Enable mouse clicking + scrolling
set -g mouse on

# Enable true color
set -g default-terminal "${TERM}"
set -as terminal-overrides ",${TERM}*:Tc"

# Pane splits should open to the same path as the current pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Show current tab as green
set-window-option -g window-status-current-style bg=green,fg=black

# Yellow/Black for pwsh, Red/Black for cmd, Default/Transparent for everything else
set -g status-style "bg=#{?#{==:#W,pwsh},yellow,#{?#{==:#W,cmd},red,default}},fg=#{?#{==:#W,pwsh},black,#{?#{==:#W,cmd},black,default}}"
