-- Resolves user/local_langs.lua against the user/languages.lua registry and
-- hands each plugin config (lsp, dap, conform, treesitter) the slice it needs.
local M = {}

local registry = require('user.languages')

local ok, enabled_list = pcall(require, 'user.local_langs')
if not ok then
  vim.notify(
    'langs: no user.local_langs (copy local_langs.lua.example to local_langs.lua): ' .. enabled_list,
    vim.log.levels.WARN
  )
  enabled_list = {}
end

local enabled = {}
for _, name in ipairs(enabled_list) do
  local lang = registry[name]
  if lang then
    enabled[name] = lang
  else
    vim.notify('langs: unknown language "' .. name .. '" in local_langs.lua', vim.log.levels.WARN)
  end
end

function M.is_enabled(name)
  return enabled[name] ~= nil
end

-- Rewrites local_langs.lua to list every language in the registry,
-- keeping currently-enabled ones uncommented and commenting out the rest.
-- Run :LangsSync after adding entries to languages.lua so new languages
-- show up without hand-editing the file.
function M.sync_local_langs()
  local names = vim.tbl_keys(registry)
  table.sort(names)

  local lines = {
    '-- Generated by :LangsSync — re-run it after languages.lua gains new',
    '-- entries. Uncomment the languages you want, then restart nvim.',
    'return {',
  }
  for _, name in ipairs(names) do
    local fmt = enabled[name] and '  "%s",' or '  -- "%s",'
    table.insert(lines, fmt:format(name))
  end
  table.insert(lines, '}')

  local path = vim.fn.stdpath('config') .. '/lua/user/local_langs.lua'
  vim.fn.writefile(lines, path)
  return path
end

function M.lsp_servers()
  local servers = {}
  for _, lang in pairs(enabled) do
    vim.list_extend(servers, lang.lsp or {})
  end
  return servers
end

function M.dap_langs()
  local out = {}
  for key, lang in pairs(enabled) do
    if lang.dap then table.insert(out, { key = key, name = lang.dap }) end
  end
  return out
end

function M.treesitter_parsers()
  local parsers, filetypes = {}, {}
  for _, lang in pairs(enabled) do
    vim.list_extend(parsers, lang.treesitter or {})
    vim.list_extend(filetypes, lang.filetypes or {})
  end
  return parsers, filetypes
end

function M.formatters_by_ft()
  local formatters = {}
  for _, lang in pairs(enabled) do
    for ft, tools in pairs(lang.formatters or {}) do
      formatters[ft] = tools
    end
  end
  return formatters
end

return M
